[default.extend-words]
mosquitto = "mosquitto"
serie = "serie"
inferrable = "inferrable"
Strack = "Strack"
Witschel = "Witschel"
mor = "mor"
MOR = "MOR"
ser = "ser"
bais = "bais"

[files]
extend-exclude = ["**/MQTT3ClientTest.java","**/mappings**.json", "**/*Mappings**.json" , "**/profiler/*.json"]